language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - oraclejdk9
  - openjdk8
  - openjdk11
before_script:
   - sudo apt install ant-optional
script:
  - ant test
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
