language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - oraclejdk10
  - oraclejdk9
script:
  - ant test
matrix:
  allow_failures:
    - jdk: openjdk8
  fast_finish: true
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
