language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - openjdk8
script:
  - ant test
notifications:
  email:
    recipients:
      - apisupport@upwork.com
    on_failure: change
