name: java-upwork-oauth2-ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: MVN Install
        run: |
          mvn install -DskipTests=true -Dgpg.skip=true
      - name: Build with Ant
        run: |
          ant test
